!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  eps: 0.3
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      eps: 0.3
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        dictitems:
          Crop_X: !!python/object/new:dynamic_reconfigure.encoding.Config
            dictitems:
              groups: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              id: 2
              max_x: 36.0
              min_x: 0.0
              name: Crop_X
              parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              parent: 0
              state: true
              type: ''
            state: []
          Crop_Y: !!python/object/new:dynamic_reconfigure.encoding.Config
            dictitems:
              groups: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              id: 3
              max_y: 4.0
              min_y: -15.0
              name: Crop_Y
              parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              parent: 0
              state: true
              type: ''
            state: []
          Crop_Z: !!python/object/new:dynamic_reconfigure.encoding.Config
            dictitems:
              groups: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              id: 4
              max_z: 6.0
              min_z: 0.15
              name: Crop_Z
              parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              parent: 0
              state: true
              type: ''
            state: []
          Translation: !!python/object/new:dynamic_reconfigure.encoding.Config
            dictitems:
              groups: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              id: 1
              name: Translation
              parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              parent: 0
              state: true
              type: ''
              x: 15.0
              y: -5.0
              z: 1.0
            state: []
        state: []
      id: 0
      min_cluster_pts: 50
      name: Default
      nearest_min_distance: 5
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      resolution: 0.3
      state: true
      type: ''
    state: []
  max_x: 36.0
  max_y: 4.0
  max_z: 6.0
  min_cluster_pts: 50
  min_x: 0.0
  min_y: -15.0
  min_z: 0.15
  nearest_min_distance: 5
  resolution: 0.3
  x: 15.0
  y: -5.0
  z: 1.0
state: []
